"""add change configuration

Revision ID: 67090e8aab67
Revises: f09bdfadf3c1
Create Date: 2025-12-17 17:43:30.077502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '67090e8aab67'
down_revision = 'f09bdfadf3c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=postgresql.ENUM('Admin', 'Manager', 'Viewer', name='roles'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=postgresql.ENUM('Admin', 'Manager', 'Viewer', name='roles'),
               nullable=True)

    # ### end Alembic commands ###
