"""add orderItem relations

Revision ID: f09bdfadf3c1
Revises: fc3015183922
Create Date: 2025-12-17 17:41:38.194653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f09bdfadf3c1'
down_revision = 'fc3015183922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orderitem',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=True),
    sa.Column('product_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orderitem')
    # ### end Alembic commands ###
